name: places
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  surf_lint_rules: ^1.5.0



dev_dependencies:
 flutter_test:
    sdk: flutter
  
dart_code_metrics: ^4.16.0
  
flutter:
  uses-material-design: true
  assets:
    - res/
    - res/images/icons/heart.svg
    - res/images/icons/ARROW.svg
    - res/images/icons/Union.svg
    - res/images/icons/Vector 95.svg
    - res/images/icons/favorite.svg
    - res/images/icons/calendar.svg

  fonts:
   - family: Roboto
     fonts:
      - asset: res/fonts/Roboto/Roboto-Regular.ttf
      - asset: res/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: res/fonts/Roboto/Roboto-Thin.ttf
        weight: 100
      - asset: res/fonts/Roboto/Roboto-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: res/fonts/Roboto/Roboto-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: res/fonts/Roboto/Roboto-Light.ttf
        weight: 300
      - asset: res/fonts/Roboto/Roboto-LightItalic.ttf
        weight: 300
        style: italic
      - asset: res/fonts/Roboto/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: res/fonts/Roboto/Roboto-Black.ttf
        weight: 900
      - asset: res/fonts/Roboto/Roboto-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: res/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - asset: res/fonts/Roboto/Roboto-Italic.ttf
        style: italic
        
   

  
